spring:
  application:
    name: sms
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: 192.168.16.131:9300
  datasource:
    name: beadwalletloan
    url: jdbc:mysql://106.14.238.126:3306/beadwalletloan?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&useServerPrepStmts=false&rewriteBatchedStatements=true
    username: root
    password: beadwallet.mysql@2016
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 4
      max-active: 32
      max-wait: 60000
      min-idle: 4
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 3000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      test-while-idle: true
      validation-query: select 1
  thymeleaf:
    cache: true
  redis:
# Redis数据库索引（默认为0）
    database: 6
# Redis服务器地址
    host: 106.14.238.126
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password: beadwalletredis
# 连接超时时间（毫秒）
    timeout: 100000
# 连接池最大连接数（使用负值表示没有限制）
    jedis:
      pool:
        max-active: 500
        max-idle: 5
        min-idle: 1
        max-wait: 100000